### ISSUE TITLE
What does it do & how does it work?

### ISSUE THREAD

**Issue by boramalper** [frrad/skyhub#44]
First of all, cool project! I would definitely be interested in it as well.

1. I saw your HN comment but couldn't understand what skyhub does exactly.
2. Based on that, I am also curious to hear more about how do you retrieve a single paper from the .zip archives inside the torrents? Do you just retrieve the whole archive instead?

Kudos again!\
Bora

**Comment by frrad** [comment]
You can do random access inside zip files if you have some metadata. In practice, this usually means downloading 2 16MB "chunks" from the torrent to access one paper. One for the metadata on the zip file you want, then using offset info from that a second is downloaded with the actual paper.

**Comment by boramalper** [comment]
Okay, dig through some code and found this:

https://github.com/frrad/skyhub/blob/fcb3e73dc3d327e9c4969c72f49b5fffe3a94028/lib/skyhub/skyhub.go#L108

I guess it comes down to how efficient Go's zip reader is, as in how much of the archive you need to download before locating the exact position of a file inside it. 

> In practice, this usually means downloading 2 16MB "chunks" from the torrent to access one paper.

Really cool, but I wonder if we can improve it further if we got a hold of the indices of *all* file positions in all archives. Do you think it'd help?

**Comment by frrad** [comment]
That seems like it would help. The amount of download per-paper could probably be reduced to just one chunk, but it would require a lot of additional metadata - offset per paper. Also you would have to download everything to create this index which seems slow.

**Comment by boramalper** [comment]
For the record, for the sample paper () whose exact size is 2,118,173 bytes, skyhub has downloaded 2,228,828 bytes, which means that the "waste" was 5.22% of the file size, which I think is incredibly interesting given how decentralised it it. Again, incredibly well done!

I believe a full-index (of a kind that I mentioned) would help with the latency but not sure if is a good idea considering it's size. I will play around with it myself and will share the results.

**Comment by frrad** [comment]
I'm pleasantly surprised it was so good! Do you have any interest in writing a "What does it do and how does it work" section for the README? :)

**Comment by boramalper** [comment]
Sorry it seems that I have overestimated it. :) In the `pieces/` directory, I see 2 .complete files of size 16.8 MB and 1 .incomplete file of the same size (let's assume 0 for now), meaning we downloaded 33.6 MB for 2 MB. Not as impressive any more, but not too bad!

I would be hacking on it this weekend for a bit for sure. =)

**Comment by frrad** [comment]
Oh yeah, sorry for all the confusing logging. I made a PR to change the README to hopefully explain what happens. Does it make sense to you?

**Comment by boramalper** [comment]
Sorry for replying late, been quite busy for a while. The readme looks great, thanks!
