### ISSUE TITLE
Changing License to AGPL

### ISSUE THREAD

**Issue by boramalper** [frrad/skyhub#46]
Would you be interested in changing its licence from GPL to AGPL?

AGPL is more suited towards server-side software as it allows the public to request the source code of the modified program that is running on a server, whereas GPL does _not_ grant this right. I think it would be nice to ensure this with skyhub.

See https://stackoverflow.com/questions/2127246/difference-between-affero-gpl-and-gplv3 for more details.

**Comment by frrad** [comment]
Seems like a good fit 👍
